version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network
  
  # Mountebank
  mountebank:
    image: bbyars/mountebank:2.6.0
    container_name: mountebank
    ports:
      - "2525:2525"
      - "4545:4545"
    command: ["mb", "--mock"]
  
  # Sales Service
  sales-service:
    image: oss-sales:latest
    container_name: oss-sales
    build:
      context: ./oss-sales
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://sales-db:3306/salesdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - sales-db
      - kafka
    # MySQL for Sales Service
    
  sales-db:
    image: mysql:8.0
    container_name: sales-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salesdb
    ports:
      - "3306:3306"
    volumes:
      - sales-data:/var/lib/mysql
      
networks:
  kafka-network:
    driver: bridge

volumes:
  sales-data:
