spring:
  datasource:
    url: jdbc:mysql://sales-db:3306/sales-dev-db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: sso-db-usr
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect