
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oss-billing-dev?useSSL=false
    username: dev2024
    password: dev2024
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        hibernate:
          dialect:org.hibernate.dialect.MySQLDialect
